name: Auto-reply to PR comments

on:
  issue_comment:
    types: [created]

jobs:
  auto-reply:
    # Only run on pull request comments
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    
    steps:
    - name: Reply to comment
      uses: actions/github-script@v7
      with:
        script: |
          const comment = context.payload.comment;
          const commenter = comment.user.login;
          
          // Don't reply to bot comments to avoid loops
          if (comment.user.type === 'Bot') {
            console.log('Skipping bot comment');
            return;
          }
          
          // Don't reply to your own bot's comments
          if (commenter === 'github-actions[bot]') {
            console.log('Skipping github-actions bot comment');
            return;
          }
          
          const replyMessage = `Thanks for your comment, @${commenter}! 🤖 
          
          We've received your feedback and will review it soon. If this is urgent, please mention a maintainer.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: replyMessage
          });