name: Comment on PR with ritwic

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get PR diff
      id: diff
      run: |
        # Get the diff for the PR
        git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt
        
        # Check if "ritwic" exists in the diff (case insensitive)
        if grep -i "ritwic" pr_diff.txt > /dev/null; then
          echo "contains_ritwic=true" >> $GITHUB_OUTPUT
        else
          echo "contains_ritwic=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Comment success on PR
      if: steps.diff.outputs.contains_ritwic == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Found ritwic in the changes!'
          })